title: Esther Loisch Consulting
defaults:
  -
    scope:
      path: "en"
    values:
      layout: english
  -
    scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

markdown: kramdown
kramdown:
  parse_block_html: true
optional_front_matter:
  remove_originals: true
